AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: 'Spotty api'

Parameters:
  DEBUG:
    Type: String
    Default: "true"
    AllowedValues:
      - "true"
      - "false"
  JwtSecret:
    Type: String
    Default: '{{resolve:ssm:JafJwtSecret:1}}'
    AllowedValues:
      - '{{resolve:ssm:JafJwtSecret:1}}'
  SpotifyClientId:
    Type: String
    Default: '{{resolve:ssm:JafSpotifyClientId:1}}'
    AllowedValues:
      - '{{resolve:ssm:JafSpotifyClientId:1}}'
  SpotifyClientSecret:
    Type: String
    Default: '{{resolve:ssm:JafSpotifySecret:1}}'
    AllowedValues:
      - '{{resolve:ssm:JafSpotifySecret:1}}'

Globals:
  Function:
    Timeout: 15
    MemorySize: 128
    Runtime: nodejs14.x
    Environment:
      Variables:
        DEBUG: !Ref DEBUG
        JwtSecret: !Ref JwtSecret
        SpotifyClientId: !Ref SpotifyClientId
        SpotifyClientSecret: !Ref SpotifyClientSecret

Resources:
  SpotifyProfileTable:
    Type: AWS::DynamoDB::Table
    DeletionPolicy: Retain
    Properties:
      TableName: SpotifyProfile
      AttributeDefinitions:
        - AttributeName: spotifyId
          AttributeType: S
      KeySchema:
        - AttributeName: spotifyId
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1

  HttpApiGateway:
    Type: AWS::Serverless::Api
    Properties:
      StageName: v1
      Cors:
        AllowHeaders: "*"
        AllowMethods: "*"
        AllowOrigin: "*"
      Domain:
        DomainName: ts.jaf-unwrapped.com
        CertificateArn: arn:aws:acm:ap-southeast-2:355151872526:certificate/12c34da1-c039-4fc4-9636-05571fdb3df9
        Route53:
          HostedZoneId: Z05897963LYPVXX455E44

  SpotifyTopFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./dist
      Handler: functions/spotifyTop.handler
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref SpotifyProfileTable
      Events:
        GetSpotifyTop:
          Type: Api
          Properties:
            Path: /spotify/top
            Method: get
            RestApiId: !Ref HttpApiGateway
        OptionsSpotifyTop:
          Type: Api
          Properties:
            Path: /spotify/top
            Method: options
            RestApiId: !Ref HttpApiGateway

  WebSocketApiGateway:
    Type: AWS::ApiGatewayV2::Api
    Properties:
      Name: jaf-spotify-WebSocketApiGateway
      Description: An Amazon API Gateway WebSocket API and an AWS Lambda function.
      ProtocolType: WEBSOCKET
      RouteSelectionExpression: $request.path
      # Domain:
      #   Route53:
      #     HostedZoneId: Z05897963LYPVXX455E44 how do I put this in WebSocketDomain
  WebSocketDomainName:
    Type: AWS::ApiGatewayV2::DomainName
    Properties:
      DomainName: ts-ws.jaf-unwrapped.com
      DomainNameConfiguration:
        - CertificateArn: arn:aws:acm:ap-southeast-2:355151872526:certificate/12c34da1-c039-4fc4-9636-05571fdb3df9
  WebSocketRoute53RecordSet:
    Type: AWS::Route53::RecordSet
    Properties:
      Name: ts-ws.jaf-unwrapped.com
      Type: A
      HostedZoneId: Z05897963LYPVXX455E44
      AliasTarget:
        EvaluateTargetHealth: false
        DNSName: !GetAtt WebSocketApiGateway.DistributionDomainName
        HostedZoneId: !GetAtt WebSocketApiGateway.DistributionHostedZoneId
  WSConnectionIntegration:
    Type: AWS::ApiGatewayV2::Integration
    Properties:
      ApiId: !Ref WebSocketApiGateway
      IntegrationType: AWS_PROXY
      IntegrationUri: !Sub arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${WSConnectionFunction}/invocations
  WSConnectionIntegration:
    Type: AWS::ApiGatewayV2::Integration
    Properties:
      ApiId: !Ref WebSocketApiGateway
      IntegrationType: AWS_PROXY
      IntegrationUri: !Sub arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${WSConnectionFunction}/invocations
  WSConnectRoute:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref WebSocketApiGateway
      RouteKey: $connect
      AuthorizationType: NONE
      OperationName: WSConnectRoute
      Target: !Join
        - '/'
        - - 'integrations'
          - !Ref WSConnectionIntegration
  WSDisconnectRoute:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref WebSocketApiGateway
      RouteKey: $disconnect
      AuthorizationType: NONE
      OperationName: WSDisconnectRoute
      Target: !Join
        - '/'
        - - 'integrations'
          - !Ref WSConnectionIntegration
  WSDisconnectRoute:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref WebSocketApiGateway
      RouteKey: $disconnect
      AuthorizationType: NONE
      OperationName: WSDisconnectRoute
      Target: !Join
        - '/'
        - - 'integrations'
          - !Ref WSConnectionIntegration

  WSConnectionFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./dist
      Handler: functions/websocketConnection.handler
      # Policies:
        # - DynamoDBCrudPolicy:
        #     TableName: !Ref SpotifyProfileTable

Outputs:
  SpotifyProfileTable:
    Description: Store spotify records in nosql
    Value: !Ref SpotifyProfileTable
  HttpApiGateway:
    Description: ApiGateway between front end requests and backend lambda
    Value: !Ref HttpApiGateway
  SpotifyTopFunction:
    Description: Get spotify top items
    Value: !Ref SpotifyTopFunction
  WebSocketApiGateway:
    Description: Websocket API between front end requests and backend lambda
    Value: !Ref WebSocketApiGateway
  WSConnectFunction:
    Description: handle WS connect
    Value: !Ref WSConnectFunction